name: MongoDB Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
       # options: --health-cmd="mongo --eval 'db.runCommand({ connectionStatus: 1 })'"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo

    - name: Run Python script
      run: |
        python main.py  
      env:
        MONGODB_URI: mongodb://localhost:27017/mydatabase  

